spring:
  profiles:
    active: local

---
#For local environment
spring:
    profiles: local
    application:
        name: uam-admin
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    datasource:
        name: uam_admin
        url: jdbc:mysql://139.198.190.164:31269/uam_admin?useUnicode=true&characterEncoding=UTF8
        username: dzjtuser
        password: mysql@dzjt2017
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    rabbitmq:
        host: 139.198.190.164
        port: 25672
        username: guest
        password: guest
    zipkin:
        enabled: true
    sleuth:
      sampler:
        percentage: 1
mybatis:
    basepackage: com.dzjt.cbs.uam.security.admin.mapper
    xmlLocation: classpath:mapper/**/*.xml

server:
    port: 7162

eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        # docker 部署开启
        prefer-ip-address: true
        ip-address: 127.0.0.1
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
                    # docker 部署开启
#            defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

client:
  bos:
    url: https://139.198.190.164:7073/dzjt-bos-rest

# 必须配置
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 120000
  ConnectTimeout: 120000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 110000

swagger:
    basepackage: com.dzjt.cbs.uam.security.admin
    service:
        name: Admin Back
        description: Admin Back后端服务
#        developer: XT


auth:
  serviceId: uam-auth
  user:
    token-header: Authorization
  client:
    id: uam-admin
    secret: 123456
    token-header: client-token

#redis-cache 相关
redis:
    pool:
         maxActive: 300
         maxIdle: 100
         maxWait: 1000
    host: 139.198.190.164
    port: 42193
    password: dzjt
    timeout: 2000
    # 服务或应用名
    sysName: uam-admin
    enable: true
    database: 0

logging:
    file: logs/application-uam-admin.log
    pattern:
      console: "%d %-5level %logger : %msg%n"
      file: "%d %-5level [%thread] %logger : %msg%n"
    level:
#        tk.mybatis: DEBUG
        com.dzjt.cbs.uam.security.admin: DEBUG

---

#For dev environment
spring:
    profiles: dev
    application:
        name: uam-admin
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    datasource:
        name: uam_admin
        url: jdbc:mysql://192.168.30.3:3306/uam_admin?useUnicode=true&characterEncoding=UTF8
        username: dzjtuser
        password: mysql@dzjt2017
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    rabbitmq:
        host: 192.168.10.2
        port: 5672
        username: guest
        password: guest
    zipkin:
        enabled: true
    sleuth:
      sampler:
        percentage: 1
mybatis:
    basepackage: com.dzjt.cbs.uam.security.admin.mapper
    xmlLocation: classpath:mapper/**/*.xml

server:
    port: 7162

eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        # docker 部署开启
        prefer-ip-address: true
        ip-address: 127.0.0.1
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
                    # docker 部署开启
#            defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
# 必须配置

client:
  bos:
    url: https://139.198.190.164:7073/dzjt-bos-rest

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 120000
  ConnectTimeout: 120000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 110000

swagger:
    basepackage: com.dzjt.cbs.uam.security.admin
    service:
        name: Admin Back
        description: Admin Back后端服务
#        developer: XT


auth:
  serviceId: uam-auth
  user:
    token-header: Authorization
  client:
    id: uam-admin
    secret: 123456
    token-header: client-token

#redis-cache 相关
redis:
    pool:
         maxActive: 300
         maxIdle: 100
         maxWait: 1000
    host: 139.198.190.164
    port: 42193
    password: dzjt
    timeout: 2000
    # 服务或应用名
    sysName: uam-admin
    enable: true
    database: 0

logging:
    file: logs/application-uam-admin.log
    pattern:
      console: "%d %-5level %logger : %msg%n"
      file: "%d %-5level [%thread] %logger : %msg%n"
    level:
        com.dzjt.cbs.uam.security.admin: ERROR